name: first_workflow
on: 
  push:
    branches: [daily-assignment]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello World"
  code-build:
    runs-on: ubuntu-latest
    steps:
      - name: code-build
        run: echo "code is building"
